In [2]:
import pandas as pd
import numpy as np

1. Write a Python program to create and display a one-dimensional array-like object containing an array of data using Pandas module

In [331]:
s=pd.Series([1,2,3,4,5])
type(s)

pandas.core.series.Series

In [5]:
s

0    1
1    2
2    3
3    4
4    5
dtype: int64

2. Write a Python program to convert a Pandas module Series to Python list and it's type.

In [6]:
l=list(s)
type(l)

list

In [7]:
l

[1, 2, 3, 4, 5]

3. Write a Python program to add, subtract, multiple and divide two Pandas Series. 

In [8]:
s1=pd.Series([1,2,3,4,5])
s2=pd.Series([1,2,3,4,5])
s1+s2

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [9]:
s1-s2

0    0
1    0
2    0
3    0
4    0
dtype: int64

In [10]:
s1*s2

0     1
1     4
2     9
3    16
4    25
dtype: int64

In [11]:
s1/s2

0    1.0
1    1.0
2    1.0
3    1.0
4    1.0
dtype: float64

4. Write a Python program to get the largest integer smaller or equal to the division of the inputs series. Sample Series: [2, 4, 6, 8, 10], [1, 3, 5, 7, 9]

In [12]:
s1//s2

0    1
1    1
2    1
3    1
4    1
dtype: int64

5. Write a Python program to convert a dictionary to a Pandas series

In [13]:
d={'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}
s=pd.Series(d)
s

a    100
b    200
c    300
d    400
e    800
dtype: int64

6. Write a Python program to convert a NumPy array to a Pandas series.

In [14]:
n=np.array([10, 20, 30, 40, 50])
type(n)

numpy.ndarray

In [15]:
s=pd.Series(n)
type(s)

pandas.core.series.Series

In [16]:
s

0    10
1    20
2    30
3    40
4    50
dtype: int32

7. Write a Python program to change the data type of given a column or a Series.

In [17]:
s1=pd.Series([1,2,'Python',4,5.12])
s1

0         1
1         2
2    Python
3         4
4      5.12
dtype: object

In [18]:
s2=pd.to_numeric(s1, errors='coerce')
s2

0    1.00
1    2.00
2     NaN
3    4.00
4    5.12
dtype: float64

8. Write a Python Pandas program to convert the first column of a DataFrame as a Series.

In [19]:
df=pd.DataFrame([{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800},{'a': 100, 'b': 200, 'c': 300, 'd': 400, 'e': 800}])
df

a    b    c    d    e
0  100  200  300  400  800
1  100  200  300  400  800

In [20]:
type(df['a'])

pandas.core.series.Series

In [21]:
df['a']

0    100
1    100
Name: a, dtype: int64

9. Write a Pandas program to convert a given Series to an array. 

In [22]:
s=pd.Series([1,2,'Python',4,5.12])
s

0         1
1         2
2    Python
3         4
4      5.12
dtype: object

In [23]:
a=np.array(s)
a

array([1, 2, 'Python', 4, 5.12], dtype=object)

# ***
10. Write a Pandas program to convert Series of lists to one Series.

In [24]:
s = pd.Series([['Red', 'Green', 'White'],
               ['Red', 'Black'],
               ['Yellow']])
s

0    [Red, Green, White]
1           [Red, Black]
2               [Yellow]
dtype: object

In [25]:
s1 = s.apply(pd.Series)
type(s1)

pandas.core.frame.DataFrame

In [26]:
s1

0      1      2
0     Red  Green  White
1     Red  Black    NaN
2  Yellow    NaN    NaN

In [28]:
s1.stack().reset_index(drop=True)

0       Red
1     Green
2     White
3       Red
4     Black
5    Yellow
dtype: object

11. Write a Pandas program to sort a given Series. 

In [3]:
s = pd.Series(['100', '200', 'python', '300.12', '400'])
print("Original Data Series:")
print(s)
new_s = pd.Series(s).sort_values()
print(new_s)

Original Data Series:
0       100
1       200
2    python
3    300.12
4       400
dtype: object
0       100
1       200
3    300.12
4       400
2    python
dtype: object


12. Write a Pandas program to add some data to an existing Series.

In [34]:
s = pd.Series(['100', '200', 'python', '300.12', '400'])

In [37]:
s.append(pd.Series([500]))

0       100
1       200
2    python
3    300.12
4       400
0       500
dtype: object

13. Write a Pandas program to create a subset of a given series based on value and condition S>2 & <8

In [102]:
s = pd.Series([0,1,2,3,4,5,6,7,8,9,10])
s[(s>2) & (s<8)]

3    3
4    4
5    5
6    6
7    7
dtype: int64

14. Write a Pandas program to change the order of index of a given series.

In [105]:
s = pd.Series(data = [1,2,3,4,5], index = ['A', 'B', 'C','D','E'])
s

A    1
B    2
C    3
D    4
E    5
dtype: int64

In [108]:
s=s.reindex(index = ['B','A','C','D','E'])
s

B    2
A    1
C    3
D    4
E    5
dtype: int64

15. Write a Pandas program to create the mean and standard deviation of the data of a given Series.

In [ ]:
s = pd.Series(data = [1,2,3,4,5,6,7,8,9,5,3])

In [109]:
s.mean()

3.0

In [110]:
s.std()

1.5811388300841898

# ***
16. Write a Pandas program to get the items of a given series not present in another given series. 

In [111]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([2, 4, 6, 8, 10])

In [113]:
r=s1[~s1.isin(s2)]
r

0    1
2    3
4    5
dtype: int64

17. Write a Pandas program to get the items which are not common of two given series.

In [117]:
s1 = pd.Series([1, 2, 3, 4, 5])
s2 = pd.Series([2, 4, 6, 8, 10])

In [119]:
# Sol1 
r=s1[~s1.isin(s2)].append(s2[~s2.isin(s1)])
r

0     1
2     3
4     5
2     6
3     8
4    10
dtype: int64

In [121]:
# sol2
s11 = pd.Series(np.union1d(s1, s2))
s22 = pd.Series(np.intersect1d(s1, s2))
r = s11[~s11.isin(s22)]
r

0     1
2     3
4     5
5     6
6     8
7    10
dtype: int64

# ***
18. Write a Pandas & Numpy program to generate a ramdom normorl distrubuted series of 20 no's and
compute the minimum, 25th percentile, median, 75th, and maximum of a given series.

In [141]:
num_state = np.random.RandomState(100)
ns = pd.Series(num_state.normal(10, 4, 20))
r=np.percentile(ns, q=[0, 25, 50, 75, 100])
r

array([ 3.00093811,  8.09463867, 10.23353705, 12.21537733, 14.61214321])

# ***
19. Write a Pandas & Numpy program to generate a series of 20 ramdom repeated intigers between 0-10 and
calculate the frequency counts of each unique value of a that series.

In [168]:
num_series = pd.Series(np.take(list('0123456789'), np.random.randint(10, size=20)))
num_series

0     9
1     9
2     4
3     1
4     0
5     6
6     2
7     2
8     3
9     5
10    7
11    5
12    0
13    8
14    3
15    4
16    6
17    0
18    3
19    6
dtype: object

In [171]:
num_series.value_counts()

6    3
3    3
0    3
2    2
5    2
9    2
4    2
1    1
7    1
8    1
dtype: int64

20. Write a Pandas program to display most frequent value in a above series and replace everything else as 'Other' in the series.

In [175]:
num_series.value_counts().idxmax()

'6'

In [176]:
num_series[num_series!=num_series.value_counts().idxmax()]='Other'
num_series

0     Other
1     Other
2     Other
3     Other
4     Other
5         6
6     Other
7     Other
8     Other
9     Other
10    Other
11    Other
12    Other
13    Other
14    Other
15    Other
16        6
17    Other
18    Other
19        6
dtype: object

# ***
21. Write a Pandas program to find the positions of numbers that are multiples of 5 of a given series.

In [213]:
num_series = pd.Series(np.random.randint(1, 10, 9))
num_series

0    1
1    5
2    2
3    5
4    8
5    5
6    1
7    7
8    2
dtype: int32

In [214]:
a=np.array(num_series)
r = np.argwhere(a%5==0) # ***
r

array([[1],
       [3],
       [5]], dtype=int64)

22. Write a Pandas program to extract items at given positions of a given series.

In [215]:
num_series = pd.Series(list('2390238923902390239023'))
element_pos = [0, 2, 6, 11, 21]

In [220]:
# Sol1
num_series.loc[[0, 2, 6, 11, 21]]

0     2
2     9
6     8
11    0
21    3
dtype: object

In [221]:
# Sol2
num_series.take(element_pos)  # ***

0     2
2     9
6     8
11    0
21    3
dtype: object

# ***
23. Write a Pandas program to get the positions of items of a given series in another given series. 

In [228]:
series1 = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
series2 = pd.Series([1, 3, 5, 7, 9])

In [231]:
result = [pd.Index(series1).get_loc(i) for i in series2]
result

[0, 2, 4, 6, 8]

24. Write a Pandas program convert the first and last character of each word to upper case in each word of a given series. 

In [232]:
series1 = pd.Series(['php', 'python', 'java', 'c#'])

In [235]:
result = series1.map(lambda x: x[0].upper() + x[1:-1] + x[-1].upper())
result

0       PhP
1    PythoN
2      JavA
3        C#
dtype: object

25. Write a Pandas program to calculate the number of characters in each word in a given series.

In [246]:
series1 = pd.Series(['Php', 'Python', 'Java', 'C#'])

In [268]:
result = series1.map(lambda x: len(x))
result

0    3
1    6
2    4
3    2
dtype: int64

# ***
26. Write a Pandas program to compute difference of differences between consecutive numbers of a given series.

In [282]:
s1 = pd.Series([1, 3, 5, 8, 10, 11, 15])
r=s1.diff().tolist()
r

[nan, 2.0, 2.0, 3.0, 2.0, 1.0, 4.0]

27. Write a Pandas program to convert a series of date strings to a timeseries.

In [285]:
date_series = pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', 
                         '2019-04-06T11:20'])
date_series

0         01 Jan 2015
1          10-02-2016
2            20180307
3          2014/05/06
4          2016-04-12
5    2019-04-06T11:20
dtype: object

In [284]:
pd.to_datetime(date_series)

0   2015-01-01 00:00:00
1   2016-10-02 00:00:00
2   2018-03-07 00:00:00
3   2014-05-06 00:00:00
4   2016-04-12 00:00:00
5   2019-04-06 11:20:00
dtype: datetime64[ns]

# ***
28. Write a Pandas program to get the day of month, day of year, week number and day of week from a given series of date strings.

In [295]:
date_series1 = pd.Series(['01 Jan 2015', '10-02-2016', '20180307', '2014/05/06', '2016-04-12', 
                         '2019-04-06T11:20'])
date_series1

0         01 Jan 2015
1          10-02-2016
2            20180307
3          2014/05/06
4          2016-04-12
5    2019-04-06T11:20
dtype: object

In [316]:
from dateutil.parser import parse
date_series = date_series1.map(lambda x: parse(x))
print("Day of month:")
print(date_series.dt.day.tolist())
print("Day of year:")
print(date_series.dt.dayofyear.tolist())
print("Week number:")
print(date_series.dt.weekofyear.tolist())
print("Day of weekday:")
print(date_series.dt.weekday.tolist())
print("Day of day name:")
print(date_series.dt.day_name().tolist())

Day of month:
[1, 2, 7, 6, 12, 6]
Day of year:
[1, 276, 66, 126, 103, 96]
Week number:
[1, 39, 10, 19, 15, 14]
Day of weekday:
[3, 6, 2, 1, 1, 5]
Day of day name:
['Thursday', 'Sunday', 'Wednesday', 'Tuesday', 'Tuesday', 'Saturday']


29. Write a Pandas program to convert year-month string to dates adding a specified day of the month.

In [319]:
date_series = pd.Series(['Jan 2015', 'Feb 2016', 'Mar 2017', 'Apr 2018', 'May 2019'])
print("Original Series:")
print(date_series)
print("\nNew dates:")
result = date_series.map(lambda d: parse('11 ' + d))
print(result)

Original Series:
0    Jan 2015
1    Feb 2016
2    Mar 2017
3    Apr 2018
4    May 2019
dtype: object

New dates:
0   2015-01-11
1   2016-02-11
2   2017-03-11
3   2018-04-11
4   2019-05-11
dtype: datetime64[ns]


# ***
30. Write a Pandas program to filter words from a given series that contain atleast two vowels.

In [320]:
from collections import Counter
color_series = pd.Series(['Red', 'Green', 'Orange', 'Pink', 'Yellow', 'White'])
print("Original Series:")
print(color_series)
print("\nFiltered words:")
result = mask = color_series.map(lambda c: sum([Counter(c.lower()).get(i, 0) for i in list('aeiou')]) >= 2)
print(color_series[result])

Original Series:
0       Red
1     Green
2    Orange
3      Pink
4    Yellow
5     White
dtype: object

Filtered words:
1     Green
2    Orange
4    Yellow
5     White
dtype: object


31. Write a Pandas program to compute the Euclidean distance between two given series.
#### From Wikipedia,
In mathematics, the Euclidean distance or Euclidean metric is the "ordinary" straight-line distance between two points in Euclidean space. With this distance, Euclidean space becomes a metric space. The associated norm is called the Euclidean norm.

In [321]:
x = pd.Series([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
y = pd.Series([11, 8, 7, 5, 6, 5, 3, 4, 7, 1])
print("Original series:")
print(x)
print(y)
print("\nEuclidean distance between two said series:")
print(np.linalg.norm(x-y))

Original series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
dtype: int64
0    11
1     8
2     7
3     5
4     6
5     5
6     3
7     4
8     7
9     1
dtype: int64

Euclidean distance between two said series:
16.492422502470642


32. Write a Pandas program to find the positions of the values neighboured by smaller values on both sides in a given series.

In [322]:
nums = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
print("Original series:")
print(nums)
print("\nPositions of the values surrounded by smaller values on both sides:")
temp = np.diff(np.sign(np.diff(nums)))
result = np.where(temp == -2)[0] + 1
print(result)


Original series:
0    1
1    8
2    7
3    5
4    6
5    5
6    3
7    4
8    7
9    1
dtype: int64

Positions of the values surrounded by smaller values on both sides:
[1 4 8]


33. Write a Pandas program to replace missing white spaces in a given string with the least frequent character. 

In [323]:
str1 = 'abc def abcdef icd'
print("Original series:")
print(str1)
ser = pd.Series(list(str1))
element_freq = ser.value_counts()
print(element_freq)
current_freq = element_freq.dropna().index[-1]
result = "".join(ser.replace(' ', current_freq))
print(result)

Original series:
abc def abcdef icd
     3
d    3
c    3
f    2
e    2
a    2
b    2
i    1
dtype: int64
abcidefiabcdefiicd


34. Write a Pandas program to compute the autocorrelations of a given numeric series.

In [324]:
num_series = pd.Series(np.arange(15) + np.random.normal(1, 10, 15))
print("Original series:")
print(num_series)
autocorrelations = [num_series.autocorr(i).round(2) for i in range(11)]
print("\nAutocorrelations of the said series:")
print(autocorrelations[1:])

Original series:
0    -12.877901
1     -0.269413
2     16.843423
3      2.710226
4     10.472366
5    -10.948717
6     11.186278
7     17.040595
8     -0.674258
9     -7.808806
10    11.707510
11    17.497710
12    20.352822
13    -0.369353
14    12.804454
dtype: float64

Autocorrelations of the said series:
[-0.04, -0.37, -0.18, 0.41, 0.43, -0.4, -0.53, 0.67, 0.39, 0.31]


35. Write a Pandas program to create a TimeSeries to display all the Sundays of given year.

In [325]:
result = pd.Series(pd.date_range('2020-01-01', periods=52, freq='W-SUN'))
print("All Sundays of 2019:")
print(result)

All Sundays of 2019:
0    2020-01-05
1    2020-01-12
2    2020-01-19
3    2020-01-26
4    2020-02-02
5    2020-02-09
6    2020-02-16
7    2020-02-23
8    2020-03-01
9    2020-03-08
10   2020-03-15
11   2020-03-22
12   2020-03-29
13   2020-04-05
14   2020-04-12
15   2020-04-19
16   2020-04-26
17   2020-05-03
18   2020-05-10
19   2020-05-17
20   2020-05-24
21   2020-05-31
22   2020-06-07
23   2020-06-14
24   2020-06-21
25   2020-06-28
26   2020-07-05
27   2020-07-12
28   2020-07-19
29   2020-07-26
30   2020-08-02
31   2020-08-09
32   2020-08-16
33   2020-08-23
34   2020-08-30
35   2020-09-06
36   2020-09-13
37   2020-09-20
38   2020-09-27
39   2020-10-04
40   2020-10-11
41   2020-10-18
42   2020-10-25
43   2020-11-01
44   2020-11-08
45   2020-11-15
46   2020-11-22
47   2020-11-29
48   2020-12-06
49   2020-12-13
50   2020-12-20
51   2020-12-27
dtype: datetime64[ns]


36. Write a Pandas program to convert given series into a dataframe with its index as another column on the dataframe.

In [326]:
char_list = list('ABCDEFGHIJKLMNOP')
num_arra = np.arange(8)
num_dict = dict(zip(char_list, num_arra))
num_ser = pd.Series(num_dict)
df = num_ser.to_frame().reset_index()
print(df.head())

  index  0
0     A  0
1     B  1
2     C  2
3     D  3
4     E  4


37. Write a Pandas program to stack two given series vertically and horizontally. 

In [327]:
series1 = pd.Series(range(10))
series2 = pd.Series(list('pqrstuvwxy'))
print("Original Series:")
print(series1)
print(series2)
series1.append(series2)
df = pd.concat([series1, series2], axis=1)
print("\nStack two given series vertically and horizontally:")
print(df)

Original Series:
0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64
0    p
1    q
2    r
3    s
4    t
5    u
6    v
7    w
8    x
9    y
dtype: object

Stack two given series vertically and horizontally:
   0  1
0  0  p
1  1  q
2  2  r
3  3  s
4  4  t
5  5  u
6  6  v
7  7  w
8  8  x
9  9  y


38. Write a Pandas program to check the equality of two given series.

In [328]:
nums1 = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
nums2 = pd.Series([1, 8, 7, 5, 6, 5, 3, 4, 7, 1])
print("Original Series:")
print(nums1)
print(nums2)
print("Check 2 series are equal or not?")
print(nums1 == nums2)

Original Series:
0    1
1    8
2    7
3    5
4    6
5    5
6    3
7    4
8    7
9    1
dtype: int64
0    1
1    8
2    7
3    5
4    6
5    5
6    3
7    4
8    7
9    1
dtype: int64
Check 2 series are equal or not?
0    True
1    True
2    True
3    True
4    True
5    True
6    True
7    True
8    True
9    True
dtype: bool


39. Write a Pandas program to find the index of the first occurrence of the smallest and largest value of a given series.

In [329]:
nums = pd.Series([1, 3, 7, 12, 88, 23, 3, 1, 9, 0])
print("Original Series:")
print(nums)
print("Index of the first occurrence of the smallest and largest value of the said series:")
print(nums.idxmin())
print(nums.idxmax())

Original Series:
0     1
1     3
2     7
3    12
4    88
5    23
6     3
7     1
8     9
9     0
dtype: int64
Index of the first occurrence of the smallest and largest value of the said series:
9
4


40. Write a Pandas program to check inequality over the index axis of a given dataframe and a given series.

In [330]:
df_data = pd.DataFrame({'W':[68,75,86,80,None],'X':[78,75,None,80,86], 'Y':[84,94,89,86,86],'Z':[86,97,96,72,83]});
sr_data = pd.Series([68, 75, 86, 80, None]) 
print("Original DataFrame:")
print(df_data)
print("\nOriginal Series:")
print(sr_data)
print("\nCheck for inequality of the said series & dataframe:")
print(df_data.ne(sr_data, axis = 0))

Original DataFrame:
      W     X   Y   Z
0  68.0  78.0  84  86
1  75.0  75.0  94  97
2  86.0   NaN  89  96
3  80.0  80.0  86  72
4   NaN  86.0  86  83

Original Series:
0    68.0
1    75.0
2    86.0
3    80.0
4     NaN
dtype: float64

Check for inequality of the said series & dataframe:
       W      X     Y     Z
0  False   True  True  True
1  False  False  True  True
2  False   True  True  True
3  False  False  True  True
4   True   True  True  True
